ASM_ASP/Controllers/BillController.cs
using ASM_ASP.IServices;
using ASM_ASP.Models;
using ASM_ASP.Services;
using Microsoft.AspNetCore.Mvc;

namespace ASM_ASP.Controllers
{
    public class BillController : Controller
    {
        private readonly ILogger<BillController> _logger;
        private readonly IBillService _billServices;
        private readonly IProductService _productServices;
        private readonly IBillDetailService _billDetailServices;
        private readonly ICartDetailService _cartDetailServices;
        public BillController(ILogger<BillController> logger)
        {
            _logger = logger;
            _billServices = new BillService();
            _productServices = new ProductService();
            _billDetailServices = new BillDetailService();
            _cartDetailServices = new CartDetailService();

        }
        public ActionResult CreateBill(Guid userId)
        {
            List<CartDetail> lstCartdetails = _cartDetailServices.GetAll().Where(c => c.UserId == userId).ToList();

            var bill = new Bill()
            {
                Id = Guid.NewGuid(),
                DateofCreation = DateTime.Now,
                UserId = userId,
                Status = 1,
            };

            if (_billServices.Create(bill))
            {
                foreach (var x in lstCartdetails)
                {
                    var billDetail = new BillDetail()
                    {
                        ProductId = x.ProductId,
                        BillId = bill.Id,
                        Quantity = x.Quantity,
                        Price = _productServices.GetAll().FirstOrDefault(c => c.Id == x.ProductId).Price,
                    };
                    _billDetailServices.Create(billDetail);
                    _cartDetailServices.Delete(x.ProductId, x.UserId);
                    var product = _productServices.GetAll().FirstOrDefault(c => c.Id == x.ProductId);
                    product.AvailableQuantity = product.AvailableQuantity - x.Quantity;
                    _productServices.Update(product);
                }

                return RedirectToAction("Show", new { billId = bill.Id });
            }
            else
            {
                return BadRequest();
            }
        }

        public IActionResult DetailsBill(Guid id)
        {
            var obj = _billServices.GetById(id);
            return View(obj);
        }
        public IActionResult ShowBill(Guid id)
        {
            var listBilldetails = _billDetailServices.GetAll();
            ViewBag.listBillDetails = listBilldetails.Where(c => c.BillId == id).ToList();
            ViewBag.listProduct = _productServices.GetAll();
            return View();
        }
    }
}

ASM_ASP/Controllers/CartController.cs
using ASM_ASP.IServices;
using ASM_ASP.Models;
using ASM_ASP.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace ASM_ASP.Controllers
{
	public class CartController : Controller
	{
        private readonly ILogger<CartController> _logger;
        private readonly ICartService _cartService;
        private readonly IProductService _productService;
        private readonly ICartDetailService _cartDetailService;
        public CartController(ILogger<CartController> logger)
        {
            _logger = logger;
            _cartService = new CartService();
            _productService = new ProductService();
            _cartDetailService = new CartDetailService();
        }
        public IActionResult Index()
		{
			return View();
		}
        public IActionResult ShowCart(Guid idUser)
        {
            //var userId = HttpContext.Session.GetString("userId");
            //ViewData["userId"] = userId;
            //if (!string.IsNullOrEmpty(userId))
            //{
            //    ViewBag.listCartDetails = _cartDetailService.GetAll().Where(c => c.UserId == Guid.Parse(userId)).ToList();
            //    ViewBag.listProduct = _productService.GetAll();
            //    return View();
            //}
            //return RedirectToAction("Login", "Home");
            idUser = Guid.Parse("8871ad42-6960-473d-aa75-aabc6edf5014");
            //if (idUser == Guid.Empty)
            //{
            //    return RedirectToAction("Index", "Home");
            //}

            var listCartDetails =  _cartDetailService.GetAll();
            ViewBag.listCartDetails = listCartDetails.Where(c => c.UserId == idUser && c.Status == 0).ToList();
            ViewBag.listProduct =  _productService.GetAll();

            return View();
        }
        public IActionResult Create(/*Guid productId*/ Guid idProduct, Guid idUser) 
        {
            //var userId = HttpContext.Session.GetString("userId");
            //Guid id = Guid.Parse(userId);
            //if (!string.IsNullOrEmpty(userId))
            //{
            //    List<CartDetail> cartDetails = _cartDetailService.GetAll().Where(c => c.UserId == id).ToList();
            //    CartDetail obj = new()
            //    {
            //        UserId = id,
            //        ProductId = productId,
            //        Quantity = 1
            //    };
            //    if (cartDetails.Any(c => c.UserId == id && c.ProductId == productId))
            //    {
            //        obj.Quantity = cartDetails.FirstOrDefault(c => c.UserId == id && c.ProductId == productId).Quantity + 1;
            //        return _cartDetailService.Update(obj.ProductId, obj.UserId, obj) ? RedirectToAction("Show") : BadRequest();
            //    }
            //    else
            //    {
            //        return _cartDetailService.Create(obj) ? RedirectToAction("Show") : BadRequest();
            //    }
            //}
            //return BadRequest();

            List<CartDetail> cartDetails =  _cartDetailService.GetAll();

            CartDetail obj = new()
            {
                UserId = idUser,
                ProductId = idProduct,
                Quantity = 1
            };

            // Check sản phẩm đã có trong giỏ hàng hay chưa
            // Nếu có => Update +1 cho Amount
            // Nếu không => Create
            if (cartDetails.Any(c => c.UserId == idUser && c.ProductId == idProduct))
            {
                // Update
                if (cartDetails.FirstOrDefault(c => c.UserId == idUser && c.ProductId == idProduct).Status == 0)
                {
                    obj.Quantity = cartDetails.FirstOrDefault(c => c.UserId == idUser && c.ProductId == idProduct).Quantity + 1;
                }

                var resultUpdate = _cartDetailService.Update(obj.ProductId, obj.UserId, obj);

                if (resultUpdate)
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                var result = _cartDetailService.Create(obj);

                if (result)
                {
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index", "Home");
        }
        public IActionResult Details(Guid productId, Guid userId)
        {
            ViewBag.cartDetails = _cartDetailService.GetById(productId, userId);

            return View();
        }

        public IActionResult Delete(Guid productId)
        {
            Guid id = Guid.Parse(HttpContext.Session.GetString("userId"));
            return _cartDetailService.Delete(productId, id) ? RedirectToAction("Show") : BadRequest();
        }

        public IActionResult Edit(CartDetail obj)
        {
            obj.UserId = Guid.Parse("00000000-0000-0000-0000-000000000000");

            var result = _cartDetailService.Update(obj.ProductId, obj.UserId, obj);

            if (result)
            {
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

ASM_ASP/Controllers/ProductController.cs
using ASM_ASP.IServices;
using ASM_ASP.Models;
using ASM_ASP.Services;
using Microsoft.AspNetCore.Mvc;

namespace ASM_ASP.Controllers
{
    public class ProductController : Controller
    {
        private readonly ILogger<ProductController> _logger;
        private readonly IProductService _productService;

        public ProductController(ILogger<ProductController> logger)
        {
            _logger = logger;
            _productService = new ProductService();
        }

        public ActionResult ShowAllProduct()
        {
            List<Product> products = _productService.GetAll();
            return View(products);
        }

        public IActionResult CreateProduct()
        {
            return View();
        }
        [HttpPost]
        public IActionResult CreateProduct(Product p, IFormFile imageFile)
        {
            // Trong trường hợp chúng ta thực hiện với thuộc tính Description
            // Thuộc tính này đang là string => Không thể thao tác trực tiếp
            // với các file => Truyền thêm 1 tham số vào Action này
            // Truyền thêm 1 tham số imageFile kiểu IFormFile
            // Bước 1: Kiểm tra đường dãn tới ảnh được lấy từ form
            if (imageFile != null && imageFile.Length > 0) // Không null không rỗng
            {
                // Thực hiện trỏ tới thư mục root để lát thực hiện việc copy
                var path = Path.Combine(Directory.GetCurrentDirectory(),
                    "wwwroot", "images", imageFile.FileName); // Bước 2
                // Kết quả: aaa/wwwroot/images/xxx.jpg, Path.Combine = tổng hợp đường dẫn
                var stream = new FileStream(path, FileMode.Create);
                // Vì chúng ta thực hiện việc copy => Tạo mới => Create
                imageFile.CopyTo(stream); // Copy ảnh chọn ở form vào wwwroot/images
                // Gán lại giá trị cho thuộc tính Description => Bước 3
                p.Description = imageFile.FileName; // Bước 4
            }
            if (_productService.Create(p))
            {
                return RedirectToAction("ShowAllProduct");
            }
            else return BadRequest();
        }

        public IActionResult DetailsProduct(Guid id)
        {
            var product = _productService.GetById(id);
            return View(product);

        }

        public IActionResult DeleteProduct(Guid id)
        {
            if (_productService.Delete(id))
            {
                return RedirectToAction("ShowAllProduct");
            }
            else return BadRequest();
        }

        [HttpGet]
        public IActionResult EditProduct(Guid id)
        {
                      
			var product = _productService.GetById(id);
			var products = SessionService.GetObjFromSession(HttpContext.Session, "History");
			var existingProduct = products.FirstOrDefault(p => p.Id == id);
			if (products.Count == 0)
			{
				products.Add(product);
				SessionService.SetObjToSession(HttpContext.Session, "History", products);
			}
			else
			{
				if (SessionService.CheckObjInList(id, products))
				{
					if (existingProduct != null)
					{
						return View(product);
					}
					else
					{
						products.Remove(existingProduct);
					}
				}
				else
				{
					products.Add(product);
					SessionService.SetObjToSession(HttpContext.Session, "History", products);
				}
			}
            return View(product);
        }
        public IActionResult EditProduct(Product p)
        {

            if (_productService.Update(p))
            {
                return RedirectToAction("ShowAllProduct");
            }
            else return BadRequest();
        }
        

        [HttpPost]
		public IActionResult CallBack(Guid id, string action)
		{
			if (action == "CallBack")
			{
				var obj = SessionService.GetObjFromSession(HttpContext.Session, "History").FirstOrDefault(p => p.Id == id);
				if (_productService.Update(obj))
            {
                return RedirectToAction("ShowAllProduct");
            }
            else return BadRequest();
        }
			else
			{
				var product = _productService.GetById(id);
				return RedirectToAction("UpdateProduct", product);
			}
		}
		public IActionResult HistoryEdit()
		{
			var products = SessionService.GetObjFromSession(HttpContext.Session, "History");
			return View(products);
		}
        public IActionResult AddToCart(Guid id)
        {
            //B1: Dua vao id lay ra san pham
            var product = _productService.GetById(id);
            //B2: Lay danh sach san pham ra tu session
            var products = SessionService.GetObjFromSession(HttpContext.Session, "Cart");
            if (products.Count == 0)
            {
                products.Add(product);// them truc tiep sp vao neu list trong
                SessionService.SetObjToSession(HttpContext.Session, "Cart", products);
            }
            else
            {
                if (SessionService.CheckObjInList(id, products))
                {//kiem tra xem list lay ra co chua sp hay chua
                    return Content("Binh thuong chung ta se them so luong nhung vi luoi nen che ma chi dua ra thong bao nay");
                }
                else
                {
                    products.Add(product);// them truc tiep sp vao neu list trong chua chua sp 
                    SessionService.SetObjToSession(HttpContext.Session, "Cart", products);
                }
            }
            //B3: Kiem tra va them san pham vao gio hang
            return RedirectToAction("ShowCart");
        }
		public IActionResult ShowCart()
        {
			//Lay du lieu tu session de truyen vao view
			var products = SessionService.GetObjFromSession(HttpContext.Session, "Cart");
			return View(products);
        }
    }
}

ASM_ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ASM_ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ASM_ASP.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.3.0/font/bootstrap-icons.css">

    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Font Awesome icons (free version)-->
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
    <!-- Google fonts-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.4/font/bootstrap-icons.css">
</head>
<body>
    <header>
        


        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3" id="mainNav">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src="~/home/img/logocon.jpg" alt="Logo" width="200px" height="100px"></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>                       
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="ShowAllProduct">Product List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="ShowCart">Cart List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Bill" asp-action="ShowBill">Bill List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Product" asp-action="HistoryEdit">History Edit List</a>
                        </li>
                    </ul>
                    <div class="navbar-nav ml-auto">
                        <div class="nav-item ">
                            <a href="@Url.Action("Login", "Home")" class="btn wishlist text-light" style="text-decoration:none;"><span>Đăng Nhập</span></a>
                            <a href="@Url.Action("Register", "Home")" class="btn cart text-light" style="text-decoration:none;"><span>Đăng Ký</span> </a>
                        </div>
                    </div>
                </div>

            </div>
        </nav>
        <div class="bottom-bar">
            <div class="container-fluid">
                <div class="row align-items-center">
                    <div class="col-md-3">
                        
                    </div>
                    <div class="col-md-3">
                    </div>
                    <div class="col-md-3">
                        <div class="user">
        
                            <a href="@Url.Action("ShowCart","Cart")" class="btn cart" style="text-decoration:none;">
                                <i class="bi bi-cart"></i></i>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer bg-dark border-top">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-4 text-lg-start text-white">Copyright &copy; Your Website 2023</div>
                <div class="col-lg-4 my-3 my-lg-0 text-center">
                    <a class="btn btn-light btn-social mx-2" href="#!" aria-label="Twitter"><i class="bi bi-twitter"></i></a>
                    <a class="btn btn-light btn-social mx-2" href="#!" aria-label="Facebook"><i class="bi bi-facebook"></i></a>
                    <a class="btn btn-light btn-social mx-2" href="#!" aria-label="LinkedIn"><i class="bi bi-youtube"></i></a>
                </div>
                <div class="col-lg-4 text-lg-end">
                    <a class="link-light text-decoration-none me-3 " href="#!">Privacy Policy</a>
                    <a class="link-light text-decoration-none" href="#!">Terms of Use</a>
                </div>
            </div>
        </div>
    </footer>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="js/scripts.js"></script>   
    <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    <!------------------>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>