ASM_ASP/Models/Cart.cs
namespace ASM_ASP.Models
{
    public class Cart
    {
        public Guid UserId { get; set; }
        public string Description { get; set; }
        public virtual ICollection<CartDetail> CartDetails { get; set; }
        public virtual User User { get; set; }
    }
}

ASM_ASP/Controllers/BillController.cs
using ASM_ASP.IServices;
using ASM_ASP.Models;
using ASM_ASP.Services;
using Microsoft.AspNetCore.Mvc;

namespace ASM_ASP.Controllers
{
    public class BillController : Controller
    {
        private readonly ILogger<BillController> _logger;
        private readonly IBillService _billServices;
        private readonly IProductService _productServices;
        private readonly IBillDetailService _billDetailServices;
        private readonly ICartDetailService _cartDetailServices;
        public BillController(ILogger<BillController> logger)
        {
            _logger = logger;
            _billServices = new BillService();
            _productServices = new ProductService();
            _billDetailServices = new BillDetailService();
            _cartDetailServices = new CartDetailService();

        }
        public ActionResult CreateBill(Guid userId)
        {
            List<CartDetail> lstCartdetails = _cartDetailServices.GetAll().Where(c => c.UserId == userId).ToList();

            var bill = new Bill()
            {
                Id = Guid.NewGuid(),
                DateofCreation = DateTime.Now,
                UserId = userId,
                Status = 1,
            };

            if (_billServices.Create(bill))
            {
                foreach (var x in lstCartdetails)
                {
                    var billDetail = new BillDetail()
                    {
                        ProductId = x.ProductId,
                        BillId = bill.Id,
                        Quantity = x.Quantity,
                        Price = _productServices.GetAll().FirstOrDefault(c => c.Id == x.ProductId).Price,
                    };
                    _billDetailServices.Create(billDetail);
                    _cartDetailServices.Delete(x.ProductId, x.UserId);
                    var product = _productServices.GetAll().FirstOrDefault(c => c.Id == x.ProductId);
                    product.AvailableQuantity = product.AvailableQuantity - x.Quantity;
                    _productServices.Update(product);
                }

                return RedirectToAction("Show", new { billId = bill.Id });
            }
            else
            {
                return BadRequest();
            }
        }

        public IActionResult DetailsBill(Guid id)
        {
            var obj = _billServices.GetById(id);
            return View(obj);
        }
        public IActionResult ShowBill(Guid id)
        {
            var listBilldetails = _billDetailServices.GetAll();
            ViewBag.listBillDetails = listBilldetails.Where(c => c.BillId == id).ToList();
            ViewBag.listProduct = _productServices.GetAll();
            return View();
        }
    }
}

ASM_ASP/Controllers/CartController.cs
using ASM_ASP.IServices;
using ASM_ASP.Models;
using ASM_ASP.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;

namespace ASM_ASP.Controllers
{
	public class CartController : Controller
	{
        private readonly ILogger<CartController> _logger;
        private readonly ICartService _cartService;
        private readonly IProductService _productService;
        private readonly ICartDetailService _cartDetailService;
        public CartController(ILogger<CartController> logger)
        {
            _logger = logger;
            _cartService = new CartService();
            _productService = new ProductService();
            _cartDetailService = new CartDetailService();
        }
        public IActionResult Index()
		{
			return View();
		}
        public IActionResult ShowCart(Guid idUser)
        {
            //var userId = HttpContext.Session.GetString("userId");
            //ViewData["userId"] = userId;
            //if (!string.IsNullOrEmpty(userId))
            //{
            //    ViewBag.listCartDetails = _cartDetailService.GetAll().Where(c => c.UserId == Guid.Parse(userId)).ToList();
            //    ViewBag.listProduct = _productService.GetAll();
            //    return View();
            //}
            //return RedirectToAction("Login", "Home");
            idUser = Guid.Parse("8871ad42-6960-473d-aa75-aabc6edf5014");
            //if (idUser == Guid.Empty)
            //{
            //    return RedirectToAction("Index", "Home");
            //}

            var listCartDetails =  _cartDetailService.GetAll();
            ViewBag.listCartDetails = listCartDetails.Where(c => c.UserId == idUser && c.Status == 0).ToList();
            ViewBag.listProduct =  _productService.GetAll();

            return View();
        }
        public IActionResult Create(/*Guid productId*/ Guid idProduct, Guid idUser) 
        {
            //var userId = HttpContext.Session.GetString("userId");
            //Guid id = Guid.Parse(userId);
            //if (!string.IsNullOrEmpty(userId))
            //{
            //    List<CartDetail> cartDetails = _cartDetailService.GetAll().Where(c => c.UserId == id).ToList();
            //    CartDetail obj = new()
            //    {
            //        UserId = id,
            //        ProductId = productId,
            //        Quantity = 1
            //    };
            //    if (cartDetails.Any(c => c.UserId == id && c.ProductId == productId))
            //    {
            //        obj.Quantity = cartDetails.FirstOrDefault(c => c.UserId == id && c.ProductId == productId).Quantity + 1;
            //        return _cartDetailService.Update(obj.ProductId, obj.UserId, obj) ? RedirectToAction("Show") : BadRequest();
            //    }
            //    else
            //    {
            //        return _cartDetailService.Create(obj) ? RedirectToAction("Show") : BadRequest();
            //    }
            //}
            //return BadRequest();

            List<CartDetail> cartDetails =  _cartDetailService.GetAll();

            CartDetail obj = new()
            {
                UserId = idUser,
                ProductId = idProduct,
                Quantity = 1
            };

            // Check sản phẩm đã có trong giỏ hàng hay chưa
            // Nếu có => Update +1 cho Amount
            // Nếu không => Create
            if (cartDetails.Any(c => c.UserId == idUser && c.ProductId == idProduct))
            {
                // Update
                if (cartDetails.FirstOrDefault(c => c.UserId == idUser && c.ProductId == idProduct).Status == 0)
                {
                    obj.Quantity = cartDetails.FirstOrDefault(c => c.UserId == idUser && c.ProductId == idProduct).Quantity + 1;
                }

                var resultUpdate = _cartDetailService.Update(obj.ProductId, obj.UserId, obj);

                if (resultUpdate)
                {
                    return RedirectToAction("Index");
                }
            }
            else
            {
                var result = _cartDetailService.Create(obj);

                if (result)
                {
                    return RedirectToAction("Index");
                }
            }

            return RedirectToAction("Index", "Home");
        }
        public IActionResult Details(Guid productId, Guid userId)
        {
            ViewBag.cartDetails = _cartDetailService.GetById(productId, userId);

            return View();
        }

        public IActionResult Delete(Guid productId)
        {
            Guid id = Guid.Parse(HttpContext.Session.GetString("userId"));
            return _cartDetailService.Delete(productId, id) ? RedirectToAction("Show") : BadRequest();
        }

        public IActionResult Edit(CartDetail obj)
        {
            obj.UserId = Guid.Parse("00000000-0000-0000-0000-000000000000");

            var result = _cartDetailService.Update(obj.ProductId, obj.UserId, obj);

            if (result)
            {
                return RedirectToAction("Index");
            }

            return View();
        }
    }
}

ASM_ASP/Views/Cart/DetailsCart.cshtml
@model ASM_ASP.Models.Cart

@{
    ViewData["Title"] = "DetailsCart";
}

<h1>DetailsCart</h1>

<div>
    <h4>CartDetail</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UserId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UserId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>       
    </dl>
</div>
<div>
    <a asp-action="ShowCart">Back to List</a>
</div>

ASM_ASP/Views/Cart/ShowCart.cshtml
@model IEnumerable<ASM_ASP.Models.CartDetail>

@{
    ViewData["Title"] = "ShowCart";
    List<CartDetail> listCartdetails = ViewBag.listCartDetails;
    List<Product> listProduct = ViewBag.listProduct;
    int total = 0;
    var index = 0;
}

<h1>Giỏ hàng</h1>

<div class="content pb-5 bg-white">
    <table class="table table-hover text-center"
           style="max-width: 1000px; margin: 0 auto;box-shadow: 0px 0px 30px grey; color: unset; table-layout: fixed; vertical-align: middle;">
        <thead class="fs-6">
            <tr>
                <th>STT</th>
                <th colspan="3">Sản phẩm</th>
                <th>Giá tiền</th>
                <th>Số lượng</th>
                <th>Thành tiền</th>
                <th colspan="2"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var productInCart in listCartdetails)
            {
                <tr>
                    <th>@(index + 1)</th>
                    <td colspan="3">
                        <div class="row p-0 m-0">
                            <div class="col-6">
                                <img class="p-2"
                                     src="~/Image/@listProduct.FirstOrDefault(c=>c.Id == productInCart.ProductId).Description"
                                     alt="product" style="object-fit: cover; max-width: 100%;height: auto;">
                            </div>
                            <div class="col-6 py-4">
                                <p class="text-start" style="text-overflow: ellipsis;">@listProduct.FirstOrDefault(c=>c.Id == productInCart.ProductId).Name</p>
                            </div>
                        </div>
                    </td>
                    <td>@listProduct.FirstOrDefault(c=>c.Id == productInCart.ProductId).Price</td>
                    <td>@productInCart.Quantity</td>
                    <td><b>@(listProduct.FirstOrDefault(c => c.Id == productInCart.ProductId).Price * productInCart.Quantity)</b></td>
                    <td colspan="2">
                        <div class="btn btn-product">
                            <a href="@Url.Action("Delete","Cart", new { productId = @productInCart.ProductId, userId="0D77B2C0-DFD1-4DA2-DF97-08DB35CDB8BE" })">Xóa</a>
                        </div>
                    </td>
                </tr>
            }
            <tr>
                <th class="text-uppercase fs-5" colspan="6">
                    Tổng thành tiền (@listCartdetails.Count())
                </th>
                <td class="fs-6">
                    <b>
                        @for (int i = 0; i < listCartdetails.Count; i++)
                        {
                            total += listCartdetails[i].Quantity * Convert.ToInt32(listProduct.FirstOrDefault(c => c.Id == listCartdetails[i].ProductId).Price);
                        }
                        @total
                    </b>
                </td>
                <td colspan="2">
                    <div class="btn btn-product">
                        <a href="@Url.Action("Create","Bill", new {userId="0D77B2C0-DFD1-4DA2-DF97-08DB35CDB8BE" })">Thanh toán</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>

</div>